_wandb:
    value:
        cli_version: 0.27.0
        code_path: code/ppo.py
        e:
            60s7k539a3lt65wl8pik765urcshvqg5:
                args:
                    - --exp-name
                    - baseline_fixed
                    - --goal-room
                    - "1"
                    - --yellow-room
                    - "off"
                    - --total-timesteps
                    - "500000"
                    - --seed
                    - "1"
                    - --track
                    - --wandb-project-name
                    - ppo-spurious
                codePath: ppo.py
                codePathLocal: ppo.py
                cpu_count: 32
                cpu_count_logical: 32
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "21407727616"
                        used: "18112585728"
                email: animeconqueror108@gmail.com
                executable: /ddnlus/barsatkhadka/World-Model-RL/venv/bin/python
                git:
                    commit: 519c4a778cc547796998834dbfd39d4ded5e7186
                    remote: https://github.com/BarsatKhadka/World-Model-RL.git
                gpu: NVIDIA L40S
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-781e10a8-9b96-6650-c559-a85263aa2bf1
                host: node047
                memory:
                    total: "540582883328"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.39
                program: /ddnlus/barsatkhadka/World-Model-RL/ppo.py
                python: CPython 3.12.3
                root: /ddnlus/barsatkhadka/World-Model-RL
                slurm:
                    array_job_id: "87972"
                    array_task_count: "6"
                    array_task_id: "0"
                    array_task_max: "5"
                    array_task_min: "0"
                    array_task_step: "1"
                    cluster_name: slurm
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_cpus_per_node: "8"
                    job_end_time: "1779565063"
                    job_gid: "1008"
                    job_gpus: "0"
                    job_id: "87973"
                    job_name: ppo_spurious_train
                    job_nodelist: node047
                    job_num_nodes: "1"
                    job_partition: gpuq
                    job_qos: normal
                    job_start_time: "1779561463"
                    job_uid: "2060"
                    job_user: barsatkhadka
                    jobid: "87973"
                    localid: "0"
                    mem_per_node: "32768"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: node047
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /ddnlus/barsatkhadka/World-Model-RL
                    submit_host: magnolia1
                    task_pid: "3341139"
                    tasks_per_node: "1"
                    topology_addr: node047
                    topology_addr_pattern: node
                    tres_per_task: cpu=8
                startedAt: "2026-05-23T18:37:46.677626Z"
                writerId: 60s7k539a3lt65wl8pik765urcshvqg5
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
                - 41
            "4": 3.12.3
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
anneal_lr:
    value: true
batch_size:
    value: 512
capture_video:
    value: false
clip_coef:
    value: 0.2
clip_vloss:
    value: true
cuda:
    value: true
ent_coef:
    value: 0.01
env_id:
    value: SpuriousFourRooms-v0
exp_name:
    value: baseline_fixed
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
goal_room:
    value: "1"
learning_rate:
    value: 0.00025
max_grad_norm:
    value: 0.5
minibatch_size:
    value: 128
norm_adv:
    value: true
num_envs:
    value: 4
num_iterations:
    value: 976
num_minibatches:
    value: 4
num_steps:
    value: 128
seed:
    value: 1
target_kl:
    value: null
torch_deterministic:
    value: true
total_timesteps:
    value: 500000
track:
    value: true
update_epochs:
    value: 4
vf_coef:
    value: 0.5
wandb_entity:
    value: null
wandb_project_name:
    value: ppo-spurious
yellow_room:
    value: "off"
